# Set programs that you use
$terminal = foot
$fileManager = dolphin
$menu = walker
$browser = firefox
$uishell = qs
$notif_daemon = mako
$wallpaper_manager = hyprpaper
$lockscreen = swaylock --color 322C2E
